### ISSUE TITLE
Storybook Broken

### ISSUE THREAD

**Issue by DennisSmolek** [pmndrs/three-stdlib#120]
When loading the [Storybook](https://three-stdlib.vercel.app/)

the page doesn't load.

Console says:
```
619.4a46c130.iframe.bundle.js:2 Uncaught TypeError: esm.ConfigApi is not a constructor
    at start (619.4a46c130.iframe.bundle.js:2:200791)
    at Object../node_modules/@storybook/html/dist/esm/client/preview/index.js (619.4a46c130.iframe.bundle.js:2:148182)
    at __webpack_require__ (runtime~main.536d0841.iframe.bundle.js:1:357)
    at Module../node_modules/@storybook/html/dist/esm/client/index.js (619.4a46c130.iframe.bundle.js:2:144149)
    at __webpack_require__ (runtime~main.536d0841.iframe.bundle.js:1:357)
    at Object../storybook-init-framework-entry.js (main.a87180a5.iframe.bundle.js:1:171140)
    at __webpack_require__ (runtime~main.536d0841.iframe.bundle.js:1:357)
    at __webpack_exec__ (main.a87180a5.iframe.bundle.js:1:171304)
    at main.a87180a5.iframe.bundle.js:1:171566
    at Function.__webpack_require__.O (runtime~main.536d0841.iframe.bundle.js:1:963)
    ```

**Comment by bjornstar** [comment]
Thanks for letting us know, I have updated the build script and redeployed, seems to be working again :)

I also added it to the Poimandres domain:

https://three-stdlib.pmnd.rs
