### ISSUE TITLE
The pkg packaging failed to run

### ISSUE THREAD

**Issue by mu116699** [pmndrs/three-stdlib#373]
Use the const {GLTFLoader} = require('three-stdlib/loaders/gltfloader.cjs'); Package and export bug reports；

use pkg package and use version "three-stdlib": "^2.30.3"

bug：pkg.exe "F:\MSC-Three-Gltf-Reader\threejs\01-first threejs app\firstapp\public\model\MX75XWPLR20240415153225.glb"
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './loaders/gltfloader.cjs' is not defined by "exports" in C:\snapshot\gltfContour\node_modules\three-stdlib\package.json
[90m    at new NodeError (node:internal/errors:372:5)[39m
[90m    at throwExportsNotFound (node:internal/modules/esm/resolve:472:9)[39m
[90m    at packageExportsResolve (node:internal/modules/esm/resolve:753:3)[39m
[90m    at resolveExports (node:internal/modules/cjs/loader:482:36)[39m
[90m    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)[39m
[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)[39m
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1943:44)
[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)[39m
[90m    at Module.require (node:internal/modules/cjs/loader:1005:19)[39m
    at Module.require (pkg/prelude/bootstrap.js:1851:31) {
  code: [32m'ERR_PACKAGE_PATH_NOT_EXPORTED'[39m

**Comment by CodyJasonBennett** [comment]
Subpath imports are not supported and are hazardous. That should be `const { GLTFLoader } = require('three-stdlib')`.
